### PR TITLE
Fix/desktop open with tool access

### LINKED ISSUE #6029: [Bug]: Additional selection in windows client necessary
### Installation Method

Local Installation

### The Problem

Opening a PDF in windows client shows the file, but in order to use any tools with the already displayed content, you have to manually select the file in the workbench a second time.

Image

It makes more sense to automatically select opened files. 

### Version of Stirling-PDF

2.8.0

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

_No response_

### Docker Configuration

```txt

```

### Relevant Log Output

```txt

```

### Additional Information

_No response_

### Browsers Affected

_No response_

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by SakShamJain8**
## Description

Fixes #6029 - Additional selection in windows client no longer necessary

## Problem
When opening PDF files in the Windows desktop client using "Open with", the file displays properly but users had to manually select it again in the workbench before any PDF tools (merge, compress, crop, compare, etc.) become functional.

## Root Cause
Files opened via "Open with" were added to FileContext but **not selected** (missing `selectFiles: true`). Without selection, the file wasn't marked as active, preventing tool access.

Additionally, `AppInitializer` was placed outside `ToolWorkflowProvider`, causing a context error.

### Changes:
1. **frontend/src/desktop/hooks/useAppInitialization.ts**
   - Added `{ selectFiles: true }` when calling `addFiles()`
   - Files now immediately marked as active in FileContext

2. **frontend/src/core/components/AppProviders.tsx**
   - Moved `AppInitializer` inside `ToolWorkflowProvider`
   - Ensures context availability for initialization

## Testing
- Open PDF via "Open with" on Windows
- File now immediately usable with all tools
- No manual reselection needed

## Screenshot
Screenshot (3)

### CODE REVIEW

File: frontend/src/core/components/AppProviders.tsx [hunk 1]
```diff
@@ -106,12 +106,12 @@ export function AppProviders({ children, appConfigRetryOptions, appConfigProvide
                 <AppConfigLoader />
                 <ServerDefaultsSync />
                 <FileContextProvider enableUrlSync={true} enablePersistence={true}>
-                  <AppInitializer />
                   <BrandingAssetManager />
                   <ToolRegistryProvider>
                       <NavigationProvider>
                         <FilesModalProvider>
                           <ToolWorkflowProvider>
+                            <AppInitializer />
```
Comment (reecebrowne) [inline frontend/src/core/components/AppProviders.tsx]: Can we move this back to where it was, there is no reason to move it

**Comment by EthanHealy01** [comment]
Hey @SakShamJain8, thanks for the work on this! I think we already fixed this independently, right around the same time (sorry haha). Could you do me a favor and pull the latest main and see if this issue is fixed for you? 

Selected files should be view scoped, so now, if you're in the viewer, the currently viewed file is the only selected file, and when a user is in the active files view, the files they ticked are the selected files (as before). This should mean that we fixed this as a byproduct, but nice catch nevertheless! 

That being said, I'm happy for this to go in and auto select files that are uploaded using "open with". Once you've made the change Reece asked for we'll merge it :)

File: frontend/src/core/components/AppProviders.tsx (hunk 1 above)
Comment (SakShamJain8) [reply frontend/src/core/components/AppProviders.tsx]: yeah we can

Comment (SakShamJain8) [reply frontend/src/core/components/AppProviders.tsx]: Hi @reecebrowne, I've updated AppInitializer in commit 99a16ad to address this. Could you please take another look?

Comment (reecebrowne) [reply frontend/src/core/components/AppProviders.tsx]: Perfect thanks!

**Review by reecebrowne — APPROVED** [review]

**Comment by reecebrowne** [comment]
> Hey @SakShamJain8, thanks for the work on this! I think we already fixed this independently, right around the same time (sorry haha). Could you do me a favor and pull the latest main and see if this issue is fixed for you?
> 
> Selected files should be view scoped, so now, if you're in the viewer, the currently viewed file is the only selected file, and when a user is in the active files view, the files they ticked are the selected files (as before). This should mean that we fixed this as a byproduct, but nice catch nevertheless!
> 
> That being said, I'm happy for this to go in and auto select files that are uploaded using "open with". Once you've made the change Reece asked for we'll merge it :)

@EthanHealy01 Your fix and this one have overlap but aren't one to one. There is still behaviour this fix helps prevent that would be nice to have in
