### PR TITLE
fix(pdf): resolve compression error and file overwrite issues

### LINKED ISSUE #2930: [Bug]: Compression error dont finish : console output
### Installation Method

Docker

### The Problem

Error compressing Microsoft Form file in PDF that weighs 1.5MB, which is indicated required in 1 MB or 500 KB and never ends. 

### Version of Stirling-PDF

0.41.0

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

_No response_

### Docker Configuration

```txt

```

### Relevant Log Output

```txt
13:52:28.565 [qtp1277946450-40] WARN  s.s.SPDF.utils.ProcessExecutor - qpdf succeeded with warnings: WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3955) is not one plus the highest object number (3953)
qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.565 [qtp1277946450-40] INFO  s.s.S.c.api.misc.CompressController - Current compression ratio: 1.28
13:52:28.567 [qtp1277946450-40] WARN  o.apache.pdfbox.pdmodel.PDDocument - You are overwriting the existing file input_9555163750972844129.pdf, this will produce a corrupted file if you're also reading from it
13:52:28.574 [qtp1277946450-40] INFO  s.s.SPDF.utils.ProcessExecutor - Running command: qpdf --optimize-images --recompress-flate --compression-level=9 --compress-streams=y --object-streams=generate /tmp/input_9555163750972844129.pdf /tmp/output_11976530846112303363.pdf
13:52:28.578 [Thread-1006] INFO  s.s.SPDF.utils.ProcessExecutor - WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3961) is not one plus the highest object number (3959)
13:52:28.652 [Thread-1006] INFO  s.s.SPDF.utils.ProcessExecutor - qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.653 [qtp1277946450-40] WARN  s.s.SPDF.utils.ProcessExecutor - qpdf succeeded with warnings: WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3961) is not one plus the highest object number (3959)
qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.654 [qtp1277946450-40] WARN  s.s.SPDF.utils.ProcessExecutor - qpdf succeeded with warnings: WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3961) is not one plus the highest object number (3959)
qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.654 [qtp1277946450-40] INFO  s.s.S.c.api.misc.CompressController - Current compression ratio: 1.28
13:52:28.655 [qtp1277946450-40] WARN  o.apache.pdfbox.pdmodel.PDDocument - You are overwriting the existing file input_9555163750972844129.pdf, this will produce a corrupted file if you're also reading from it
13:52:28.662 [qtp1277946450-40] INFO  s.s.SPDF.utils.ProcessExecutor - Running command: qpdf --optimize-images --recompress-flate --compression-level=9 --compress-streams=y --object-streams=generate /tmp/input_9555163750972844129.pdf /tmp/output_11976530846112303363.pdf
13:52:28.665 [Thread-1008] INFO  s.s.SPDF.utils.ProcessExecutor - WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3967) is not one plus the highest object number (3965)
13:52:28.741 [Thread-1008] INFO  s.s.SPDF.utils.ProcessExecutor - qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.743 [qtp1277946450-40] WARN  s.s.SPDF.utils.ProcessExecutor - qpdf succeeded with warnings: WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3967) is not one plus the highest object number (3965)
qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.743 [qtp1277946450-40] WARN  s.s.SPDF.utils.ProcessExecutor - qpdf succeeded with warnings: WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3967) is not one plus the highest object number (3965)
qpdf: operation succeeded with warnings; resulting file may have some problems
13:52:28.743 [qtp1277946450-40] INFO  s.s.S.c.api.misc.CompressController - Current compression ratio: 1.28
13:52:28.745 [qtp1277946450-40] WARN  o.apache.pdfbox.pdmodel.PDDocument - You are overwriting the existing file input_9555163750972844129.pdf, this will produce a corrupted file if you're also reading from it
13:52:28.752 [qtp1277946450-40] INFO  s.s.SPDF.utils.ProcessExecutor - Running command: qpdf --optimize-images --recompress-flate --compression-level=9 --compress-streams=y --object-streams=generate /tmp/input_9555163750972844129.pdf /tmp/output_11976530846112303363.pdf
13:52:28.756 [Thread-1010] INFO  s.s.SPDF.utils.ProcessExecutor - WARNING: /tmp/input_9555163750972844129.pdf: reported number of objects (3973) is not one plus the highest object number (3971)
```

### Additional Information

The docker must be forced but an infinite loop of numbered errors.

### Browsers Affected

_No response_

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by Abdurrahman-shaikh**
# Description of Changes

- **What was changed:**
  - Modified the file handling logic to avoid overwriting the source PDF while it is being read, which previously led to corrupted output files.
  -Modified the logic where optimizeLevel is 9 and we are chacking for optimizeLevel < 9.
- **Why the change was made:**
  - The original compression process would stuck when dealing with larger files, failing to meet the specified target size limits.
  - Overwriting the input file during processing was causing warnings and potential file corruption, which could lead to instability and incorrect outputs.

- **Any challenges encountered:**

Closes #2930

---

### General

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have read the [Stirling-PDF Developer Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/DeveloperGuide.md) (if applicable)
- [] I have read the [How to add new languages to Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md) (if applicable)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### Documentation

- [] I have updated relevant docs on [Stirling-PDF's doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/) (if functionality has heavily changed)
- [] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### UI Changes (if applicable)

- [ ] Screenshots or videos demonstrating the UI changes are attached (e.g., as comments or direct attachments in the PR)

### Testing (if applicable)

- [x] I have tested my changes locally

### CODE REVIEW

File: src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java [hunk 1]
```diff
@@ -94,7 +95,9 @@ private void compressImagesInPDF(Path pdfFile, double initialScaleFactor) throws
                     }
                 }
             }
-            doc.save(pdfFile.toString());
+            Path tempOutput = Files.createTempFile("output_", ".pdf");
```
Comment (Frooodle) [inline src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java:98]: tempOutput needs to be cleaned up in a try finally

**Review by Frooodle — CHANGES_REQUESTED** [review]

**Review by Frooodle — APPROVED** [review]

File: src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java (hunk 1 above)
Comment (Frooodle) [reply src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java:98]: Nevermind i see you replace existing PDF afterwards

**Review by DarioGii — APPROVED** [review]
