### PR TITLE
Fix image stamp cropping and align preview with PDF output for add-stamp

### LINKED ISSUE #5968: [Bug]: Image stamp gets cropped in Automation pipeline
### Installation Method

_No response_

### The Problem

When I place an image stamp in the top-right corner using the "Add Image Stamp" step inside an Automation pipeline, the stamp image gets noticeably cropped/cut off at the top and right edges.

What I've observed:
- The stamp works correctly when using the "Add Image Stamp" function as a standalone tool (positioning and scaling are fine).
- The issue only occurs when the same stamp step is part of an Automation workflow.
- Adding transparent padding around the stamp image does not stop the cropping
- Adjusting margin settings does not resolve the issue either.

### Version of Stirling-PDF

2.7.0

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

_No response_

### Docker Configuration

```txt
latest-fat Docker image
```

### Relevant Log Output

```txt

```

### Additional Information

_No response_

### Browsers Affected

_No response_

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by Dexterity104**
# Description of Changes

## Summary

- **Backend:** Image stamps are positioned using lower-left PDF coordinates (`drawImage`). Replaced shared text/baseline Y logic with `calculateImagePositionY`, fixed horizontal centre using `lowerLeftX`, and clamped `(x, y)` so the full bitmap stays inside the media box (grid and custom overrides).

- **Frontend:** Preview image size now matches the API (`fontSize` as height in pt, no alphabet scale). Drag and override seeding clamp using page size minus stamp dimensions. Page size uses `getViewport({ scale: 1, rotation: 0 })` to match media-box axes and thumbnails; image rotation preview uses lower-left pivot like the server.

## Why

Users saw image stamps clipped (especially top-right) and different spacing than the preview. Automate and standalone both call the same endpoint, but the preview and server disagreed on anchor math, scale, bounds, and viewport rotation. This change aligns coordinate systems and sizing so the rendered PDF matches what people configure.

## Testing

- Manual: Add Stamp -> image -> quick top-right / centre / custom drag near edges; compare preview to resulting PDF
- Automated: `./gradlew :stirling-pdf:test --tests "stirling.software.SPDF.controller.api.misc.StampControllerTest"` (includes image Y positioning tests)

Closes #5968

---

### General

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have read the [Stirling-PDF Developer Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/DeveloperGuide.md) (if applicable)
- [x] I have read the [How to add new languages to Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/HowToAddNewLanguage.md) (if applicable)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### Documentation

- [ ] I have updated relevant docs on [Stirling-PDF's doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/) (if functionality has heavily changed)
- [x] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### Translations (if applicable)

- [ ] I ran [`scripts/counter_translation.py`](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/docs/counter_translation.md)

### UI Changes (if applicable)

- [ ] Screenshots or videos demonstrating the UI changes are attached (e.g., as comments or direct attachments in the PR)

### Testing (if applicable)

- [x] I have tested my changes locally. Refer to the [Testing Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/DeveloperGuide.md#6-testing) for more details.
image

image

### CODE REVIEW

**Comment by Frooodle** [comment]
Thanks on raising and following up with a fix so quick on this! Great work

**Comment by Dexterity104** [comment]
@Frooodle , @Ludy87 , @jbrunton96 , @ConnorYoh , @reecebrowne , @EthanHealy01 
This PR is ready for review when you have time. Thanks!

**Review by mahdirajaee — COMMENTED** [review]
Well-structured fix across both the backend and frontend. The core issue — `drawImage()` placing the lower-left corner at `(x, y)` while `calculatePositionY` was computing coordinates assuming a different anchor — is correctly addressed by introducing a dedicated `calculateImagePositionY` that accounts for `imageHeight` offset from the top. The boundary clamping logic (`Math.min(xMax, Math.max(llx, x))`) in `addImageStamp` is a good safety net to prevent stamps from being placed outside the page bounds, and it properly respects non-zero media box origins via `getLowerLeftX()`/`getLowerLeftY()`. On the frontend side, changing `getViewport({ scale: 1, rotation: 0 })` to force an unrotated viewport prevents width/height swaps that would misalign the preview. The drag clamping update from `containerSize.width` to `containerSize.width - widthPx` is the right fix to prevent stamps from being dragged off-edge. The `transformOrigin` switch to `left bottom` for images aligns the CSS rotation with the PDF coordinate system. Good unit test coverage for the new Y calculation method, including the non-zero origin case.

**Comment by Dexterity104** [comment]
Hi @Frooodle , @Ludy87 , @jbrunton96 , @ConnorYoh , @reecebrowne , @EthanHealy01
Is there any problem in my PR?

**Review by Frooodle — APPROVED** [review]

File: app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java [hunk 1]
```diff
@@ -483,9 +483,19 @@ private void addImageStamp(
             y = overrideY;
         } else {
             x = calculatePositionX(pageSize, position, desiredPhysicalWidth, margin);
-            y = calculatePositionY(pageSize, position, desiredPhysicalHeight, margin);
```
Comment (hernandezramirezluis175-crear) [inline app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java:486]: Hola qué tal

File: app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java [hunk 2]
```diff
@@ -483,9 +483,19 @@ private void addImageStamp(
...
+            // drawImage() places the lower-left corner at (x, y); use image-specific Y logic
+            y = calculateImagePositionY(pageSize, position, desiredPhysicalHeight, margin);
         }
 
+        float llx = pageSize.getLowerLeftX();
```
Comment (hernandezramirezluis175-crear) [inline app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java:490]: Hola

**Review by hernandezramirezluis175-crear — COMMENTED** [review]
Solitar cambio

File: app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java (hunk 2 above)
Comment (hernandezramirezluis175-crear) [inline app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java:490]: ????

Comment (hernandezramirezluis175-crear) [reply app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java:490]: ?
