### PR TITLE
Fix: Whitelist health endpoints in Security and Enterprise Filter

### LINKED ISSUE #5159: /health and /actuator/health endpoints return 401 when security is enabled (2.0.3 regression)
It seems it's a regression between 2.02 and 2.03

## Description

When `security.enableLogin: true` is set, all standard health endpoints require authentication and return HTTP 401. This breaks Kubernetes liveness/readiness probes, Docker healthchecks, and load balancer health checks.

## Affected Endpoints

| Endpoint | Expected | Actual |
|----------|----------|--------|
| `/health` | 200 | 401 |
| `/actuator/health` | 200 | 401 |
| `/healthz` | 200 | 401 |
| `/readiness` | 200 | 401 |
| `/liveness` | 200 | 401 |

## Workaround

Using `/api/v1/info/status` which returns `{"version": "2.0.3", "status": "UP"}` without authentication.

## Expected Behavior

Health check endpoints should be whitelisted from authentication to support:
- Kubernetes liveness/readiness probes
- Docker HEALTHCHECK
- Load balancer health checks
- Orchestration platforms

## Environment

- Version: 2.0.3-fat
- Security: `enableLogin: true` with OAuth2/OIDC
- Platform: Kubernetes

## Suggested Fix

Add health endpoints to the security whitelist in `SecurityConfiguration.java`:
```java
.antMatchers("/health", "/actuator/health", "/healthz", "/liveness", "/readiness").permitAll()
```

### PR DESCRIPTION
**Pull request by B4S1C-Coder**
# Description of Changes

This PR fixes #5159 by allowing standard health check endpoints to be accessed without authentication, which is required for container orchestration (Kubernetes/Docker) liveness and readiness probes.

Changes:

1. **Security Whitelist (RequestUriUtils):** Added `/actuator/health`, `/healthz`, `/liveness`, and `/readiness` to the public whitelist to prevent 401 Unauthorized.

2. **Enterprise Filter (EnterpriseEndpointFilter):** Added an exception for health endpoints. Previously, this filter was aggressively blocking all /actuator/ requests for non-Pro users, returning 404 Not Found even if the security config was correct.

**Testing:** Verified locally.

**Before:** `curl http://localhost:8080/actuator/health` returned `401 Unauthorized`.
**After:** curl `http://localhost:8080/actuator/health` returns `200 OK` and `{"status":"UP"}`.

A sample response from cURL:
After the fix
```bash
$ curl -v http://localhost:8080/actuator/health
```
Now returns:
```bash
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /actuator/health HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 15 Dec 2025 18:39:18 GMT
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Request-Id: 775fb1ee-35de-400d-9e8b-bd1805e3c61a
< Content-Type: application/vnd.spring-boot.actuator.v3+json
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Transfer-Encoding: chunked
<
* Connection #0 to host localhost left intact
{"status":"UP"}
```

---

### General

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have read the [Stirling-PDF Developer Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/DeveloperGuide.md) (if applicable)
- [x] I have read the [How to add new languages to Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/HowToAddNewLanguage.md) (if applicable)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### Documentation
**NOT APPLICABLE**
- [ ] I have updated relevant docs on [Stirling-PDF's doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/) (if functionality has heavily changed)
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### UI Changes (if applicable)
**NOT APPLICABLE**
- [ ] Screenshots or videos demonstrating the UI changes are attached (e.g., as comments or direct attachments in the PR)

### Testing (if applicable)

- [x] I have tested my changes locally. Refer to the [Testing Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/DeveloperGuide.md#6-testing) for more details.

### CODE REVIEW

File: app/proprietary/src/main/java/stirling/software/proprietary/security/filter/EnterpriseEndpointFilter.java [hunk 1]
```diff
@@ -26,8 +26,18 @@ protected void doFilterInternal(
             throws ServletException, IOException {
 
         if (!runningProOrHigher && isPrometheusEndpointRequest(request)) {
-            response.setStatus(HttpStatus.NOT_FOUND.value());
-            return;
+            // Allow only health checks to pass through for non-pro users
+            String uri = request.getRequestURI();
+            boolean isHealthCheck =
+                    uri.contains("/actuator/health")
+                            || uri.contains("/healthz")
```
Comment (Frooodle) [inline app/proprietary/src/main/java/stirling/software/proprietary/security/filter/EnterpriseEndpointFilter.java]: dont want to just just a contains here would prefer a more secure check like startsWith or Equals etcat least

Comment (B4S1C-Coder) [reply app/proprietary/src/main/java/stirling/software/proprietary/security/filter/EnterpriseEndpointFilter.java]: I now use startsWith for /actuator/health and equals for the remaining

**Comment by B4S1C-Coder** [comment]
Hi @Frooodle I believe I have addressed the changes regarding URL Matching. Please let me know if there's anything else needed to be done to get this merged :)

File: app/proprietary/src/main/java/stirling/software/proprietary/security/filter/EnterpriseEndpointFilter.java [hunk 2]
```diff
@@ -26,8 +26,26 @@ protected void doFilterInternal(
...
+            // Strip the context path
+            String contextPath = request.getContextPath();
+            String trimmedUri =
+                    (contextPath != null && uri.startsWith(contextPath))
+                            ? uri.substring(contextPath.length())
+                            : uri;
+
+            boolean isHealthCheck =
+                    trimmedUri.startsWith("/actuator/health")
+                            || "/healthz".equals(trimmedUri)
```
Comment (DarioGii) [inline app/proprietary/src/main/java/stirling/software/proprietary/security/filter/EnterpriseEndpointFilter.java:42]: Can you add `/health` here too for consistency?
```suggestion
                            || "/health".equals(trimmedUri)
                            || "/healthz".equals(trimmedUri)
```

**Review by DarioGii — DISMISSED** [review]
Thanks for this PR! Left a small suggestion

**Comment by B4S1C-Coder** [comment]
Applied the suggestion! Thanks for the review.

**Review by Frooodle — DISMISSED** [review]
