### PR TITLE
Fix: Access to Swagger UI when login enabled

### LINKED ISSUE #5125: Swagger UI Fails When SECURITY_ENABLELOGIN=true — Always Shows “Failed to load remote configuration"
Summary

When enabling login/security in Stirling-PDF using SECURITY_ENABLELOGIN=true (or via /configs), the built-in Swagger UI at:

/swagger-ui/index.html

stops working completely.
It shows:

Unable to render this definition.
Failed to load remote configuration.

The API itself works when sending X-API-KEY from Postman or n8n, but the Swagger UI and /v1/api-docs endpoint cannot be accessed even with valid authentication.

This behaviour only occurs when login/security is enabled.

Environment

Stirling-PDF Version: latest (Docker)

Deployment: Docker (Portainer + Nginx Proxy Manager)

Security Settings:

environment:
  - DOCKER_ENABLE_SECURITY=false
  - DISABLE_ADDITIONAL_FEATURES=false
  - SECURITY_ENABLELOGIN=true

Reverse Proxy: Nginx Proxy Manager

Browser tested: Chrome, Edge

Direct access tested:

https://domain/swagger-ui/index.html → fails

http://LOCAL-IP:8080/swagger-ui/index.html → fails with CORS error

What Works

✔ The API works correctly when sending X-API-KEY header.
✔ n8n and Postman successfully call protected endpoints.
✔ Login page works and authentication works.

What Fails

❌ Swagger UI fails with:

Unable to render this definition
Failed to load remote configuration.

Internally, the browser console shows:

Failed to load resource
/v1/api-docs/swagger-config → 401 Unauthorized

emoving login makes Swagger work

If I remove:

- SECURITY_ENABLELOGIN=true

Swagger UI works perfectly again.

→ This confirms the issue is tied specifically to login/security.

### PR DESCRIPTION
**Pull request by DarioGii**
Fixes for /swagger-ui/index.html & /v1/api-docs endpoints not being accessible when login was enabled.

- `UserAuthenticationFilter.isPublicAuthEndpoint()` had gaps in its check, missing `/v1/api-docs`
- Refactored `UserAuthenticationFilter` to use `RequestUriUtils.isPublicAuthEndpoint()` instead of its own incorrect method 

Closes #5125 & #5028

---

### Testing (if applicable)

- [x] I have tested my changes locally. Refer to the [Testing Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/devGuide/DeveloperGuide.md#6-testing) for more details.

### CODE REVIEW

File: app/common/src/main/java/stirling/software/common/util/RequestUriUtils.java [hunk 1]
```diff
@@ -162,9 +162,9 @@ public static boolean isPublicAuthEndpoint(String requestURI, String contextPath
                 // enableLogin)
                 || trimmedUri.startsWith(
                         "/api/v1/ui-data/footer-info") // Public footer configuration
-                || trimmedUri.startsWith("/v1/api-docs")
                 || trimmedUri.startsWith("/api/v1/invite/validate")
                 || trimmedUri.startsWith("/api/v1/invite/accept")
+                || trimmedUri.startsWith("/v1/api-docs")
                 || trimmedUri.contains("/v1/api-docs");
```
Comment (jbrunton96) [inline app/common/src/main/java/stirling/software/common/util/RequestUriUtils.java]: We only need one of these lines, surely?

**Review by jbrunton96 — APPROVED** [review]
