### PR TITLE
2728 bug signed rotated document different than preview

### LINKED ISSUE #2728: [Bug]: Signed rotated document different than preview
### Installation Method

None

### How to reproduce

1. Use the rotate tool on a document
2. Load the rotated document into the sign tool
3. Sign the document

### Expected 

Exported document same as sign tool preview
preview sign on rotated pdf

### Current result

The signature is not at the same spot and rotated than on the preview
[test_pdf_rotated_signed.pdf](https://github.com/user-attachments/files/18453525/test_pdf_rotated_signed.pdf)

### Version of Stirling-PDF

0.37.1

### Last Working Version of Stirling-PDF

_No response_

### Page Where the Problem Occurred

https://stirlingpdf.io/sign

### Docker Configuration

```txt

```

### Relevant Log Output

```txt

```

### Additional Information

_No response_

### Browsers Affected

Firefox

### No Duplicate of the Issue

- [x] I have verified that there are no existing issues raised related to my problem.

### PR DESCRIPTION
**Pull request by ConnorYoh**
# Description of Changes

Please provide a summary of the changes, including:

- Change the maths for accounting for rotation in add image and sign.
- Images are now placed in the expected place

Closes #2728 

---

### General

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have read the [Stirling-PDF Developer Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/DeveloperGuide.md) (if applicable)
- [x] I have read the [How to add new languages to Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md) (if applicable)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### Documentation

- [ ] I have updated relevant docs on [Stirling-PDF's doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/) (if functionality has heavily changed)
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

### UI Changes (if applicable)

- [ ] Screenshots or videos demonstrating the UI changes are attached (e.g., as comments or direct attachments in the PR)

### Testing (if applicable)

- [ ] I have tested my changes locally. Refer to the [Testing Guide](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/DeveloperGuide.md#6-testing) for more details.

### CODE REVIEW

File: src/main/resources/static/js/draggable-utils.js [hunk 1]
```diff
@@ -569,51 +565,58 @@ const DraggableUtils = {
...
-            -Math.sin(radians),
-            Math.cos(radians),
+            Math.cos(rotationInRadians),
+            Math.sin(rotationInRadians),
+            -Math.sin(rotationInRadians),
+            Math.cos(rotationInRadians),
             0,
             0
-          ),
-          PDFLib.concatTransformationMatrix(1, 0, 0, 1, -1 * originx, -1 * originy)
```
Comment (reecebrowne) [inline src/main/resources/static/js/draggable-utils.js:609]: You're a pixel off, the minus 1 here accounts for the border of the signature draggable

**Review by reecebrowne — APPROVED** [review]
